### ISSUE TITLE
Build fails due to "Module 'IDnowSDK' not found" error

### ISSUE THREAD

**Issue by bagbyte** [vino4all/cordova-plugin-idnow#1]
Hi,
I'm trying to use your plugin with Capacitor/Cordova, but the build fails in XCode with the error Module 'IDnowSDK' not found.

I've tried both:
1. Adding the pod and the post_install in the Podfile as described in the official [repo](https://github.com/idnow/de.idnow.ios)
2. Just installing your plugin and build

I'm getting always the same error, I've also tried to delete the cache and the DerivedData folder.

Am I doing something wrong or is something missing?

![Error](https://image.ibb.co/nq36Kq/Screenshot-2018-11-22-at-07-43-08.png)
![Podfile](https://image.ibb.co/e6dHQV/Screenshot-2018-11-22-at-07-43-35.png)

**Comment by adriansaenz** [comment]
This is a mess, the problem lies in cocoapods. We've had the same problem and We noticed that was necessary to make cocoapods installing the dependencies through cocoapods itself. Try to make a pod install in cocoapods folder.

**Comment by vino4all** [comment]
Closing this issue as the reported problem is because of the cocoapods dependency manager.
